
#ifndef CAN_DRV_FILTER_COMMON_H
#define CAN_DRV_FILTER_COMMON_H

#define CAN_DRV_STR_SIZE			0x80
#define CAN_DRV_FILTER_NAME			"can_drv_filter"
#define CAN_DRV_FILTER_MCAST_GROUP_NAME "can_drv_mc_grp"
#define CAN_DRV_FILTER_VERSION_NR	1

#define CAN_DRV_FILTER_DIR_NONE		0x00
#define CAN_DRV_FILTER_DIR_TX		0x01
#define CAN_DRV_FILTER_DIR_RX		0x02
#define CAN_DRV_FILTER_DIR_BOTH		(CAN_DRV_FILTER_DIR_TX|CAN_DRV_FILTER_DIR_RX)
#define CAN_DRV_FILTER_DIR_MAX		CAN_DRV_FILTER_DIR_BOTH

enum {
	CAN_DRV_FILTER_ACT_ALLOW,
	CAN_DRV_FILTER_ACT_DROP,
	__CAN_DRV_FILTER_ACT_MAX,
};

#define CAN_DRV_FILTER_ACT_MAX	(__CAN_DRV_FILTER_ACT_MAX - 1)

enum {
	CAN_DRV_FILTER_LOG_NONE,
	CAN_DRV_FILTER_LOG_CRITICAL,
	CAN_DRV_FILTER_LOG_ERROR,
	CAN_DRV_FILTER_LOG_WARN,
	CAN_DRV_FILTER_LOG_INFO,
	CAN_DRV_FILTER_LOG_DEBUG,
	__CAN_DRV_FILTER_LOG_MAX,
};

#define CAN_DRV_FILTER_LOG_MAX	(__CAN_DRV_FILTER_LOG_MAX - 1)

enum {
	CAN_DRV_FILTER_ATTR_DEV,
	CAN_DRV_FILTER_ATTR_MSG_ID,
	CAN_DRV_FILTER_ATTR_DIR,
	CAN_DRV_FILTER_ATTR_LOG,
	CAN_DRV_FILTER_ATTR_LOG_STRING,
	CAN_DRV_FILTER_ATTR_PROG,
	CAN_DRV_FILTER_ATTR_USER,
	CAN_DRV_FILTER_ATTR_ACTION,
	CAN_DRV_FILTER_ATTR_RATE,
	CAN_DRV_FILTER_ATTR_EVENT,
	CAN_DRV_FILTER_ATTR_DEFAULT,
	__CAN_DRV_FILTER_ATTR_MAX,
};

#define CAN_DRV_FILTER_ATTR_MAX	(__CAN_DRV_FILTER_ATTR_MAX - 1)

enum {
	CAN_DRV_FILTER_CMD_UNSPEC,
	CAN_DRV_FILTER_CMD_ADD,
	CAN_DRV_FILTER_CMD_DEL,
	CAN_DRV_FILTER_CMD_MOD,
	CAN_DRV_FILTER_CMD_ENABLE,
	CAN_DRV_FILTER_CMD_DISABLE,
	__CAN_DRV_FILTER_CMD_MAX,
};
#define CAN_DRV_FILTER_CMD_MAX (__CAN_DRV_FILTER_CMD_MAX - 1)

#endif /* CAN_DRV_FILTER_COMMON_H */
